### ISSUE TITLE
Better way of defining durations

### ISSUE THREAD

**Issue by godwhoa** [piqueserver/piqueserver#330]
Would be better UX if we can define duration like this
```toml
[antijerk]
ban_duration = "15min"
```
instead of 
```toml
[antijerk]
ban_duration = 15 # in minutes 
```
Library: https://github.com/wroberts/pytimeparse
